//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trial.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trial.Domain.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string CodPhone {
            get {
                return ResourceManager.GetString("CodPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User Role.
        /// </summary>
        public static string Combo_SelectRole {
            get {
                return ResourceManager.GetString("Combo_SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/Person.
        /// </summary>
        public static string CompanyPerson {
            get {
                return ResourceManager.GetString("CompanyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        public static string Corporation {
            get {
                return ResourceManager.GetString("Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End.
        /// </summary>
        public static string DateEnd {
            get {
                return ResourceManager.GetString("DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Start.
        /// </summary>
        public static string DateStart {
            get {
                return ResourceManager.GetString("DateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data concurrency conflict.
        /// </summary>
        public static string Db_Concurrency {
            get {
                return ResourceManager.GetString("Db_Concurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate value in the database.
        /// </summary>
        public static string Db_Duplicate {
            get {
                return ResourceManager.GetString("Db_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General database error.
        /// </summary>
        public static string Db_Error {
            get {
                return ResourceManager.GetString("Db_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference error, invalid foreign key.
        /// </summary>
        public static string Db_Reference {
            get {
                return ResourceManager.GetString("Db_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request.
        /// </summary>
        public static string Error_BadRequest {
            get {
                return ResourceManager.GetString("Error.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string Error_Default {
            get {
                return ResourceManager.GetString("Error.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have permission to perform this operation.
        /// </summary>
        public static string Error_Forbidden {
            get {
                return ResourceManager.GetString("Error.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found.
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        public static string Error_ServerError {
            get {
                return ResourceManager.GetString("Error.ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is unavailable.
        /// </summary>
        public static string Error_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Error.ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out.
        /// </summary>
        public static string Error_Timeout {
            get {
                return ResourceManager.GetString("Error.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in to perform this operation.
        /// </summary>
        public static string Error_Unauthorized {
            get {
                return ResourceManager.GetString("Error.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have access to the system.
        /// </summary>
        public static string Generic_AccessDenied {
            get {
                return ResourceManager.GetString("Generic_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve authenticated user&apos;s email.
        /// </summary>
        public static string Generic_AuthEmailFail {
            get {
                return ResourceManager.GetString("Generic_AuthEmailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user identifier.
        /// </summary>
        public static string Generic_AuthIdFail {
            get {
                return ResourceManager.GetString("Generic_AuthIdFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to access this resource.
        /// </summary>
        public static string Generic_AuthRequired {
            get {
                return ResourceManager.GetString("Generic_AuthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user role.
        /// </summary>
        public static string Generic_AuthRoleFail {
            get {
                return ResourceManager.GetString("Generic_AuthRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corporation you are trying to access is inactive, Please contact the system administrator.
        /// </summary>
        public static string Generic_CorporationInactive {
            get {
                return ResourceManager.GetString("Generic_CorporationInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already associated with another account.
        /// </summary>
        public static string Generic_EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("Generic_EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General exception with no specific cause.
        /// </summary>
        public static string Generic_Exception {
            get {
                return ResourceManager.GetString("Generic_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malformed or invalid request.
        /// </summary>
        public static string Generic_Http_BadRequest {
            get {
                return ResourceManager.GetString("Generic_Http_BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find what you were looking for.
        /// </summary>
        public static string Generic_IdNotFound {
            get {
                return ResourceManager.GetString("Generic_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Generic_InvalidCredentials {
            get {
                return ResourceManager.GetString("Generic_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be an issue with the information provided.
        /// </summary>
        public static string Generic_InvalidId {
            get {
                return ResourceManager.GetString("Generic_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the data submitted.
        /// </summary>
        public static string Generic_InvalidModel {
            get {
                return ResourceManager.GetString("Generic_InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to access a null value.
        /// </summary>
        public static string Generic_NullException {
            get {
                return ResourceManager.GetString("Generic_NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your plan has expired, please renew your account.
        /// </summary>
        public static string Generic_PlanExpired {
            get {
                return ResourceManager.GetString("Generic_PlanExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was deleted, but the image was not removed.
        /// </summary>
        public static string Generic_RecordDeletedNoImage {
            get {
                return ResourceManager.GetString("Generic_RecordDeletedNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything was completed successfully.
        /// </summary>
        public static string Generic_Success {
            get {
                return ResourceManager.GetString("Generic_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later.
        /// </summary>
        public static string Generic_UnexpectedError {
            get {
                return ResourceManager.GetString("Generic_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is temporarily blocked.
        /// </summary>
        public static string Generic_UserBlocked {
            get {
                return ResourceManager.GetString("Generic_UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the user. Please try again.
        /// </summary>
        public static string Generic_UserCreationFail {
            get {
                return ResourceManager.GetString("Generic_UserCreationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve user data.
        /// </summary>
        public static string Generic_UserFail {
            get {
                return ResourceManager.GetString("Generic_UserFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is inactive. Please contact the system administrator.
        /// </summary>
        public static string Generic_UserInactive {
            get {
                return ResourceManager.GetString("Generic_UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is active but has no role assigned.
        /// </summary>
        public static string Generic_UserNoRoleAssigned {
            get {
                return ResourceManager.GetString("Generic_UserNoRoleAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup server did not respond.
        /// </summary>
        public static string Http_Error_BadGateway {
            get {
                return ResourceManager.GetString("Http.Error.BadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data submitted.
        /// </summary>
        public static string Http_Error_BadRequest {
            get {
                return ResourceManager.GetString("Http.Error.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        public static string Http_Error_Default {
            get {
                return ResourceManager.GetString("Http.Error.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don’t have permission to access this.
        /// </summary>
        public static string Http_Error_Forbidden {
            get {
                return ResourceManager.GetString("Http.Error.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not respond in time.
        /// </summary>
        public static string Http_Error_GatewayTimeout {
            get {
                return ResourceManager.GetString("Http.Error.GatewayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the submitted information.
        /// </summary>
        public static string Http_Error_InvalidData {
            get {
                return ResourceManager.GetString("Http.Error.InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found.
        /// </summary>
        public static string Http_Error_NotFound {
            get {
                return ResourceManager.GetString("Http.Error.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an error. Try again later.
        /// </summary>
        public static string Http_Error_ServerError {
            get {
                return ResourceManager.GetString("Http.Error.ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is temporarily unavailable.
        /// </summary>
        public static string Http_Error_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Http.Error.ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request took too long.
        /// </summary>
        public static string Http_Error_Timeout {
            get {
                return ResourceManager.GetString("Http.Error.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must log in again.
        /// </summary>
        public static string Http_Error_Unauthorized {
            get {
                return ResourceManager.GetString("Http.Error.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string Http_Title_BadGateway {
            get {
                return ResourceManager.GetString("Http.Title.BadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string Http_Title_BadRequest {
            get {
                return ResourceManager.GetString("Http.Title.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Http_Title_Default {
            get {
                return ResourceManager.GetString("Http.Title.Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string Http_Title_Forbidden {
            get {
                return ResourceManager.GetString("Http.Title.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Http_Title_GatewayTimeout {
            get {
                return ResourceManager.GetString("Http.Title.GatewayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        public static string Http_Title_InvalidData {
            get {
                return ResourceManager.GetString("Http.Title.InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string Http_Title_LoginError {
            get {
                return ResourceManager.GetString("Http.Title.LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string Http_Title_NotFound {
            get {
                return ResourceManager.GetString("Http.Title.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Error.
        /// </summary>
        public static string Http_Title_ServerError {
            get {
                return ResourceManager.GetString("Http.Title.ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Unavailable.
        /// </summary>
        public static string Http_Title_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Http.Title.ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Timeout.
        /// </summary>
        public static string Http_Title_Timeout {
            get {
                return ResourceManager.GetString("Http.Title.Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Http_Title_Unauthorized {
            get {
                return ResourceManager.GetString("Http.Title.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Position.
        /// </summary>
        public static string JobPosition {
            get {
                return ResourceManager.GetString("JobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ModeloConfirmPassword {
            get {
                return ResourceManager.GetString("ModeloConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string ModeloCurrentPassword {
            get {
                return ResourceManager.GetString("ModeloCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string ModeloNewPassword {
            get {
                return ResourceManager.GetString("ModeloNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User Type.
        /// </summary>
        public static string ModeloSelectUserRole {
            get {
                return ResourceManager.GetString("ModeloSelectUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role User.
        /// </summary>
        public static string RoleUser {
            get {
                return ResourceManager.GetString("RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Plan.
        /// </summary>
        public static string SoftPlan {
            get {
                return ResourceManager.GetString("SoftPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        public static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trials Count.
        /// </summary>
        public static string TrialsCount {
            get {
                return ResourceManager.GetString("TrialsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Document.
        /// </summary>
        public static string TypeDocument {
            get {
                return ResourceManager.GetString("TypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be between {2} and {1} characters long.
        /// </summary>
        public static string Validation_BetweenLength {
            get {
                return ResourceManager.GetString("Validation_BetweenLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email address.
        /// </summary>
        public static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field {0} cannot be longer than {1} characteres.
        /// </summary>
        public static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field {0} must be at least {1} characters long.
        /// </summary>
        public static string Validation_MinLength {
            get {
                return ResourceManager.GetString("Validation_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match, please check.
        /// </summary>
        public static string Validation_PasswordMismatch {
            get {
                return ResourceManager.GetString("Validation_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Field {0} is required.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
    }
}
